# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8299a93ede2143629f6447d566543d736a4405f27421ade7e8063092b038b5dc8e56d1465f4e332daed7b743881504752e7d6d4d4c5830569eeb88b8d9f8e4d5

test:
  secret_key_base: 0b6840138610df24749b3a969568770dcd71f4868fd008f93ee0a6341a434347ea0a9fd483c33b00c4d769d7daa4155ccfb1207b3a0c119caf11fb24884b5490

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
